spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    password: mysecretpassword
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update