# $ docker run --detach --name mycontainer -p 61616:61616 -p 8161:8161 --rm apache/activemq-artemis:latest-alpine
version: '3.9'
services:
  activemq-artemis:
    image: apache/activemq-artemis:latest-alpine
    container_name: activemq-artemis
    ports:
      - 61616:61616
      - 8161:8161
